# -*- coding: utf-8 -*-
"""Breast..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eI_CBs1_o74KEXsSqKDs1_u-bXNYFCdo
"""

!pip install scikit-learn --upgrade
!pip install scikit-learn --upgrade
!pip install scikeras --upgrade

import sklearn as sk

from sklearn.model_selection import train_test_split
import pandas as pd
import tensorflow as tf
import scikeras as sc

pd.__version__, sk.__version__, tf.__version__, sc.__version__

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as k
from tensorflow.keras.layers import InputLayer, Dense, Dropout

X = pd.read_csv('entradas_breast.csv')
y = pd.read_csv('saidas_breast.csv')

classifier = Sequential()
classifier.add(InputLayer(shape=(30,)))
classifier.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classifier.add(Dropout(rate=0.2))
classifier.add(Dense(units=1, activation='sigmoid'))

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

classifier.fit(X, y, batch_size=10, epochs=100)

#You have to put the values here
new = np.array([15.80, 8.34, 118...])

prevision = classifier.predict(new)

if prevision > 0.5:
  print('Maligno')
else:
  print('Benigno')