# -*- coding: utf-8 -*-
"""Breast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfYtKCnf-1aTzfoXOemWDkqdkc6dILPp
"""

import sklearn as sk
sk.__version__
from sklearn.model_selection import train_test_split
import pandas as pd

pd.__version__

#input
X = pd.read_csv('/content/entradas_breast.csv')
X

#class
y = pd.read_csv('/content/saidas_breast.csv')
y

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

import tensorflow as tf
tf.__version__
from tensorflow.keras.models import Sequential

tf.__version__

#(30+1)/2

rede_neural = Sequential([
  tf.keras.layers.Input(shape=(30,)),
  tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
  tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
  tf.keras.layers.Dense(units=1, activation='sigmoid')
])

rede_neural.summary()

"""480= 30*16 (30 neurônios da camada de entrada e 16 são os neurônios da camada de Oculto)
Ou seja, foi adicionada a rede de Bias nessa rede Neural no valor de 16 (496-480). Existe um neurônio adicional ligando a cada neurônio da camada de entrada.

Temos cada neurônio ligado a saída. Assim, temos 17 parâmetros. 17 - 16 parâmetros da unidade da camada densa, temos um neurônio Bias.
"""

optimize = tf.keras.optimizers.Adam(learning_rate=0.0001, clipvalue=0.5)

rede_neural.compile(optimize, loss='binary_crossentropy', metrics = ['binary_accuracy'])

rede_neural.fit(X_train, y_train, batch_size=10, epochs=100)

previsoes = rede_neural.predict(X_test)
previsoes = previsoes > 0.5
previsoes

y_test

from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, previsoes)

confusion_matrix(y_test, previsoes)

48 + 80, 10+2

128/140, 15/140

rede_neural.evaluate(X_test, y_test)